version: "3"

services:
  app:
    build:
      context: .
    ports:
      - 8000:8000
    command: >
      sh -c " python manage.py makemigrations &&
              python manage.py migrate &&
              python manage.py shell < tools/create_superuser.py &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./core:/core
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password

  redis:
    image: redis:alpine

  celery:
    restart: always
    build:
      context: .
    command: celery -A core worker -l info
    volumes:
      - ./core:/core
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - app

  # celery-beat:
  #   restart: always
  #   build:
  #     context: .
  #   command: celery -A core beat -l INFO --scheduler django_celery_beat.schedulers:DatabaseScheduler
  #   volumes:
  #     - ./core:/core
  #   env_file:
  #     - .env
  #   depends_on:
  #     - db
  #     - redis
  #     - app